version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: gnuboard
            MYSQL_USER: gnuboard
            MYSQL_PASSWORD: strongpwd
            MYSQL_ROOT_PASSWORD: superpwd
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
    php:
        container_name: php
        build:
            context: ./build/php
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "9000:9000"
        volumes:
            - ./gnuboard5:/var/www/html
    nginx:
        container_name: nginx
        build:
            context: ./build/nginx
            dockerfile: Dockerfile
        volumes:
            - ./gnuboard5:/var/www/html
            - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
